name: deploy

on:
  push:

jobs:
  deploy: # деплой на prod сервер
    # на сервер выкладываем только ветку master
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    # выкладываем, только если проверка успешна
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        
      - name: Get ENVs
        uses: actions/checkout@v3
        with:
          repository: 'romanus21/touristic-api-envs'
          path: ./envs
          ref: master
          token: ${{ secrets.GIT_TOKEN }}
          
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: romanusus/touristics-api:latest
        
      - name: Start Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: "${{ secrets.HOST_NAME }}@${{ secrets.HOST }}"
          ssh_private_key: ${{ secrets.SSH_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
          stack_file_name: docker-compose.yml
          docker_login_password: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_login_user: ${{ secrets.DOCKERHUB_USERNAME }}
          args: -p touristics-api up --pull always -d 
